tasks:
    images:
        build:
            services:
                web:
                    image: docker.io/sroze/cp-demo-symfony
                    naming_strategy: sha1
    deployment:
        deploy:
            cluster: ${CLUSTER}
            services:
                web:
                    specification:
                        accessibility:
                            from_external: true
                        environment_variables:
                            - name: SYMFONY_ENV
                              value: prod

pipelines:
    - name: Production
      condition: 'not(code_reference.branch matches "/^cpdev/")'
      tasks: [ images, deployment ]
      variables:
          - name: SYMFONY_ENV
            value: prod
    - name: Remote
      condition: 'code_reference.branch matches "/^cpdev/"'
      tasks: [ images, deployment ]
      variables:
          - name: SYMFONY_ENV
            value: dev


