tasks:
    images:
        build:
            services:
                web:
                    image: docker.io/sroze/cp-demo-symfony
                    naming_strategy: sha1
    deployment:
        deploy:
            cluster: ${CLUSTER}
            services:
                web:
                    specification:
                        accessibility:
                            from_external: true

pipelines:
    - name: Production
      condition: 'not(code_reference.branch matches "/^cpdev/")'
      tasks: [ images, deployment ]
    - name: Remote
      condition: 'not(not(code_reference.branch matches "/^cpdev/"))'
      tasks: [ images, deployment ]



