version: "2"
services:
    web:
        image: quay.io/continuouspipe/symfony:3-apache_v1
        expose:
            - 80
            - 443
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - .:/app
